profile

diff --git a/shell/profile.d/unix-shell-script-kit b/shell/profile.d/unix-shell-script-kit
--- a/shell/profile.d/unix-shell-script-kit
+++ b/shell/profile.d/unix-shell-script-kit
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck disable=SC2034
 
 # Unix shell script kit.
 #
@@ -33,9 +34,9 @@
 # ## Tracking
 #
 #   * Package: unix-shell-script-kit
-#   * Version: 12.1.1
+#   * Version: 12.3.0
 #   * Created: 2017-08-22T00:00:00Z
-#   * Updated: 2023-08-21T18:37:56Z
+#   * Updated: 2024-12-10T23:09:11Z
 #   * License: GPL-2.0 or GPL-3.0 or contact us for more
 #   * Website: https://github.com/sixarm/unix-shell-script-kit
 #   * Contact: Joel Parker Henderson (joel@sixarm.com)
@@ -115,6 +116,7 @@ EXIT_SUCCESS=0
 # E.g. an error, an abort, found no results, lack of data, etc.
 #
 # Exit 1 meaning failure is a widespread convention as a catch-all code.
+#
 EXIT_FAILURE=1
 
 # Usage
@@ -417,6 +419,94 @@ EXIT_CODE_INVALID=128
 EXIT_CODE_INVALID=128
 
 ##
+# Color helpers
+##
+
+# ANSI escape color codes. Use these directly. Do not use "tput".
+#
+# Example:
+#
+#     printf "%sblack\n" $COLOR_BLACK
+#     printf "%sred\n" $COLOR_RED
+#     printf "%sgreen\n" $COLOR_GREEN
+#     printf "%syellow\n" $COLOR_YELLOW
+#     printf "%sblue\n" $COLOR_BLUE
+#     printf "%smagenta\n" $COLOR_MAGENTA
+#     printf "%scyan\n" $COLOR_CYAN
+#     printf "%swhite\n" $COLOR_WHITE
+#
+# For the widest support, use the basic set of 8 colors below,
+# and respect the user preferences by using the color() function.
+#
+# Many terminals also support "bright" or "bold" colors;
+# these colors have their own set of codes, similar to the
+# basic colors yet with an additional ;1 in their codes.
+# We do not recommend using these colors in your shell scripts,
+# because so many users prefer to set their own terminal colors.
+
+# Reset all color information
+COLOR_RESET='[0m'
+
+# Basic Foreground
+COLOR_BLACK='[30m'
+COLOR_RED='[31m'
+COLOR_GREEN='[32m'
+COLOR_YELLOW='[33m'
+COLOR_BLUE='[34m'
+COLOR_MAGENTA='[35m'
+COLOR_CYAN='[36m'
+COLOR_WHITE='[37m'
+
+# Basic Background
+COLOR_BG_BLACK='[40m'
+COLOR_BG_RED='[41m'
+COLOR_BG_GREEN='[42m'
+COLOR_BG_YELLOW='[43m'
+COLOR_BG_BLUE='[44m'
+COLOR_BG_MAGENTA='[$5m'
+COLOR_BG_CYAN='[46m'
+COLOR_BG_WHITE='[47m'
+
+# color: should the program use color?
+#
+# The color logic heuristic in order of priority:
+# 1. If NO_COLOR is set to non-empty, then no.
+# 2. If CLICOLOR_FORCE is set to non-empty, then yes.
+# 3. If the TERM is set to "dumb", then no.
+# 4. If the output is on a terminal, then yes.
+# 5. Otherwise, no.
+#
+color() {
+        if [ -n "${NO_COLOR:-}" ]; then return 0; fi
+        if [ -n "${CLICOLOR_FORCE:-}" ]; then return 1; fi
+        if [ "${TERM:-}" = "dumb" ]; then return 0; fi
+        return 1
+}
+
+# Set standard output color start/stop and standard error color start/stop.
+# These variables are used by the out() function and err() function below.
+#
+# If you wish to set these in your terminal, and your terminal supports
+# dollar strings with \E meaning escape, then you can use the following:
+#
+#     export STDOUT_COLOR_START=$'\E[34m'
+#     export STDOUT_COLOR_STOP=$'\E[0m'
+#     export STDERR_COLOR_START=$'\E[31m'
+#     export STDERR_COLOR_STOP=$'\E[0m'
+#
+if color; then
+        : ${STDOUT_COLOR_START='[34m'}
+        : ${STDOUT_COLOR_STOP='[0m'}
+        : ${STDERR_COLOR_START='[31m'}
+        : ${STDERR_COLOR_STOP='[0m'}
+else
+        : ${STDOUT_COLOR_START=''}
+        : ${STDOUT_COLOR_STOP=''}
+        : ${STDERR_COLOR_START=''}
+        : ${STDERR_COLOR_STOP=''}
+fi
+
+##
 # Input/output helpers
 ##
 
@@ -438,7 +528,7 @@ EXIT_CODE_INVALID=128
 #   * Use the `err` function to print to STDERR.
 #
 out() {
-        printf %s\\n "$*"
+        printf %s%s%s\\n "${STDOUT_COLOR_START:-}" "$*" "${STDOUT_COLOR_STOP:-}"
 }
 
 # err: print error message to stderr.
@@ -459,7 +549,7 @@ out() {
 #   * Use the `err` function to print to STDERR.
 #
 err() {
-        >&2 printf %s\\n "$*"
+        >&2 printf %s%s%s\\n "${STDERR_COLOR_START:-}" "$*" "${STDERR_COLOR_STOP:-}"
 }
 
 # die: print error message to stderr, then exit with error code.
@@ -470,8 +560,22 @@ err() {
 # STDERR=> my message
 # => exit 1
 # ```
+#
+# Example with an exit code number and name:
+# ```
+# die $EXIT_UNAVAILABLE EXIT_UNAVAILABLE
+# STDERR=> EXIT_UNAVAILABLE
+# => exit 69
+# ```
+#
+# Example with more information:
+# ```
+# false || die $? "Fatal error $? on line $LINENO of $0"
+# STDERR=> Fatal error 1 on line 2 of example.sh"
+# => exit 1
+# ```
 die() {
-        n="$1" ; shift ; >&2 printf %s\\n "$*" ; exit "$n"
+       n="$1" ; shift ; err "$*"; exit "$n"
 }
 
 # big: print a big banner to stdout, good for human readability.
@@ -526,7 +630,103 @@ zid() {
 # => prompt
 # ```
 ask() {
-        read x ; echo "$x" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'
+        read -r x ; echo "$x" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'
+}
+
+# utf8: should the program print UTF-8 characters such as accents and emoji?
+#
+# This implementation is a heuristic and subject to change as we learn more.
+# This checks the locale charmap. However, it's possible for the charmap to
+# be set to UTF-8, but the terminal is unable to render UTF-8 characters.
+#
+# Example:
+# ```
+# utf8
+# => true
+# ```
+utf8() {
+        if [ "$(locale charmap)" = "UTF-8" ]; then return 0; fi
+        return 1
+}
+
+##
+# Print messages with pretty formatting, colors, emojis, etc.
+##
+
+# Set pretty display of messages for success, warning, failure.
+#
+# If you wish to set these in your terminal, and your terminal supports
+# dollar strings with \E meaning escape, then you can use the following:
+#
+#     export PRINT_SUCCESS_START=$'\E[32m✅ Success: '
+#     export PRINT_SUCCESS_START=$'\E[35m⚠️ Warning: '
+#     export PRINT_FAILURE_START=$'\E[31m❌ Failure: '
+#
+if color && utf8; then
+        : ${PRINT_SUCCESS_START='[32m✅ Success: '}
+        : ${PRINT_SUCCESS_STOP='[0m'}
+        : ${PRINT_WARNING_START='[33m⚠️ Warning: '}
+        : ${PRINT_WARNING_START='[0m'}
+        : ${PRINT_FAILURE_START='[31m❌ Failure: '}
+        : ${PRINT_FAILURE_STOP='[0m'}
+else
+        : ${PRINT_SUCCESS_START='Success: '}
+        : ${PRINT_SUCCESS_STOP=''}
+        : ${PRINT_WARNING_START='Warning: '}
+        : ${PRINT_WARNING_START=''}
+        : ${PRINT_FAILURE_START='Failure: '}
+        : ${PRINT_FAILURE_STOP=''}
+fi
+
+# print_success: print a success message to stdout.
+# 
+# Example:
+# ```
+# print_success "This is a success message."
+# => This is a success message.
+# ```
+#
+# The output can be customized by setting:
+#
+#  * PRINT_SUCCESS_START
+#  * PRINT_SUCCESS_STOP
+#
+print_success() {
+        printf %s%s%s\\n "${PRINT_SUCCESS_START:-}" "$*" "${PRINT_SUCCESS_STOP:-}"
+}
+
+# print_warning: print a warning message to stdout.
+# 
+# Example:
+# ```
+# print_warning "This is a warning message."
+# => This is a warning message.
+# ```
+#
+# The output can be customized by setting:
+#
+#  * PRINT_WARNING_START
+#  * PRINT_WARNING_STOP
+#
+print_warning() {
+        printf %s%s%s\\n "${PRINT_WARNING_START:-}" "$*" "${PRINT_WARNING_STOP:-}"
+}
+
+# print_failure: print a failure message to stdout.
+# 
+# Example:
+# ```
+# print_failure "This is a failure message."
+# => This is a failure message.
+# ```
+#
+# The output can be customized by setting:
+#
+#  * PRINT_FAILURE_START
+#  * PRINT_FAILURE_STOP
+#
+print_failure() {
+        printf %s%s%s\\n "${PRINT_FAILURE_START:-}" "$*" "${PRINT_FAILURE_STOP:-}"
 }
 
 ##
@@ -562,8 +762,8 @@ ask() {
 # because this script sends the args along to the system "date" command.
 # For example Linux GNU "date" handles this, but macOS BSD "date" doesn't.
 #
+# shellcheck disable=SC2120
 now() {
-        # shellcheck disable=SC2120
         date -u "+%Y-%m-%dT%H:%M:%S.%N+00:00" "$@" | sed 's/N/000000000/'
 }
 
@@ -776,7 +976,7 @@ command_version_exists_or_die() {
 # var_exists FOO
 # => false
 # ```
-var() {
+var_exists() {
         ! eval 'test -z ${'$1'+x}'
 }
 
@@ -1752,6 +1952,38 @@ assert_str_ends_with() {
         [ "$1" != "${1%"$2"}" ] || err assert_str_ends_with "$@"
 }
 
+# assert_eval_int_eq_x: assert an eval into an integer is equal to an expression.
+#
+# Example:
+# ```
+# assert_eval_int_eq_x 'echo "1"' 1
+# => success i.e. no output
+#
+# assert_eval_int_eq_x 'echo "1"' 2
+# STDERR=> assert_eval_int_eq_x echo "1" 2
+# ```
+assert_eval_int_eq_x() {
+	if [ ! "$(eval "$1")" -eq "$2" ]; then
+                err assert_eval_int_eq_x "$@"
+	fi
+}
+
+# assert_eval_str_eq_x: assert an eval into a string is equal to an expression.
+#
+# Example:
+# ```
+# assert_eval_str_eq_x 'echo "foo"' foo
+# => success i.e. no output
+#
+# assert_eval_str_eq_x 'echo "foo"' bar
+# STDERR=> assert_eval_str_eq_x echo "foo" bar
+# ```
+assert_eval_str_eq_x() {
+	if [ ! "$(eval "$1")" = "$2" ]; then
+                err assert_eval_str_eq_x "$@"
+	fi
+}
+
 ##
 # Make temp helpers
 ##
@@ -1926,10 +2158,14 @@ file_ends_with_newline() {
 #
 user_dir(){
 	upper=$(printf %s\\n "$1" | tr '[:lower:]' '[:upper:]')
+	x=$(set +u; eval printf "%s\\\\n" \$${upper}_DIR)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$${upper}_HOME)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$XDG_${upper}_DIR)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$XDG_${upper}_HOME)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
 	lower=$(printf %s\\n "$1" | tr '[:upper:]' '[:lower:]')
-	a=$(eval printf "%s\\\\n" \$${upper}_DIR)
-	b=$(eval printf "%s\\\\n" \$${upper}_HOME)
-	c=$(eval printf "%s\\\\n" \$XDG_${upper}_DIR)
-	d=$(eval printf "%s\\\\n" \$XDG_${upper}_HOME)
-        printf %s\\n "${a:=${b:=${c:=${d:=$HOME/$lower}}}}"
+        printf %s\\n "$HOME/$lower"
 }
