posix check not the wrapper

diff --git a/wrappers/nvm b/wrappers/nvm
--- a/wrappers/nvm
+++ b/wrappers/nvm
@@ -1,8 +1,26 @@
 #!/bin/sh
+TARGET="nvm"
 
-if [ -s "$NVM_DIR"/nvm.sh ] && ! [ "$NVM_LOADED" ]; then
+if [ -s "$NVM_DIR/nvm.sh" ] && ! [ "$NVM_LOADED" ]; then
   NVM_LOADED=1
-  . "$NVM_DIR"/nvm.sh
+  . "$NVM_DIR/nvm.sh"
 fi
 
-nvm $@
+wrapper="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/$(basename "$0")"
+
+prog=""
+IFS=":"
+for p in $PATH; do
+  b="$p/$TARGET"
+  if [ "$b" != "$wrapper" ] && [ -x "$b" ]; then
+    prog="$b"
+    break
+  fi
+done
+
+if [ -z "$prog" ]; then
+  echo "'$TARGET' not found in PATH" >&2
+  exit 1
+fi
+
+"$prog" "$@"
