apps

diff --git a/scripts/setup/setup-nvim b/scripts/setup/setup-nvim
--- a/scripts/setup/setup-nvim
+++ b/scripts/setup/setup-nvim
@@ -1,6 +1,8 @@
 #!/bin/sh
-NVIM_PREFIX="${NVIM_PREFIX:-"/opt"}"
-NVIM_DIR="${NVIM_DIR:-"nvim-linux-x86_64"}"
+NVIM_PREFIX="${NVIM_PREFIX:-"/usr/local"}"
+
+archive="nvim-linux-x86_64.tar.gz"
+latest="https://github.com/neovim/neovim/releases/latest/download/$archive"
 
 die() {
   errMsg="$1"
@@ -15,18 +17,21 @@ die() {
   exit 1
 }
 
-_tmp="$(mktemp)"
-if [ "$?" != 0 ]; then
+if ! [ -d "$NVIM_PREFIX" ]; then
+  die "invalid installation prefix (\$NVIM_PREFIX=$NVIM_PREFIX)"
+fi
+
+tmp="$(mktemp)" ||
   die "failed to create tmpfile"
-fi
 
-_latest="https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
-curl -sLo "$_tmp" "$_latest" || die "failed to download" "$_tmp"
+curl -sLo "$tmp" "$latest" ||
+  die "failed to download" "$tmp"
 
-if [ -n "$NVIM_PREFIX" ] && [ -n "$NVIM_DIR" ]; then
-  sudo rm -rf "$NVIM_PREFIX"/"$NVIM_DIR" || die "failed to delete previous version at '$NVIM_PREFIX/$NVIM_DIR'" "$_tmp"
-fi
+tar -xzf "$tmp" --strip-components=1 -C "$NVIM_PREFIX" 2>/dev/null ||
+  die "failed to extract into '$NVIM_PREFIX' (use sudo?)" "$tmp"
 
-sudo tar -C "$NVIM_PREFIX" -xzf "$_tmp" || die "failed to extract" "$_tmp"
+rm -rf "$tmp" ||
+  die "failed to delete '$tmp'"
 
-rm -rf "$_tmp" || die "failed to delete '$_tmp'"
+ln -sf "$NVIM_PREFIX"/bin/nvim "$NVIM_PREFIX"/bin/vim ||
+  die "failed to create symbolic link"
