stab

diff --git a/scripts/ffmpeg-stabilize b/scripts/ffmpeg-stabilize
--- a/scripts/ffmpeg-stabilize
+++ b/scripts/ffmpeg-stabilize
@@ -1,39 +1,50 @@
 #!/bin/sh
-PROG="$0"
-input="$1"
-log=".stab.log"
+prog="$0"
+inputs="$@"
 
-die() {
-  printf '\e[2m[%s]\e[0m \e[31merror:\e[0m %s\n' "$PROG" "$1"
-  exit 1
+error() {
+  printf '\e[2m[%s]\e[0m \e[31merror:\e[0m %s\n' "$prog" "$1"
 }
 
-if ! [ -f "$input" ]; then
-  die "bad file '$input'"
-fi
+for input in $inputs; do
+  if ! [ -f "$input" ]; then
+    error "bad file '$input'"
+    continue
+  fi
 
-_ext="${input##*.}"
-_base="${input%.*}"
-output="$_base-stab.$_ext"
+  _ext="${input##*.}"
+  _base="${input%.*}"
+  output="$_base-stab.$_ext"
 
-trf="$(mktemp)" || die "cannot create temp transforms file"
+  if ! trf="$(mktemp)"; then
+    error "cannot create temp transforms file"
+    continue
+  fi
 
-if [ -z "$trf" ] || ! [ -f "$trf" ]; then
-  die "bad temp transforms file '$trf'"
-fi
+  if [ -z "$trf" ] || ! [ -f "$trf" ]; then
+    error "bad temp transforms file '$trf'"
+    continue
+  fi
 
-echo "stabilizing: $input -> $output"
+  echo "stabilizing: $input -> $output"
 
-codec=$(ffprobe -v error \
-  -select_streams v:0 \
-  -show_entries stream=codec_name \
-  -of default=noprint_wrappers=1:nokey=1 \
-  "$input") || die "failed to get codec"
+  if ! codec=$(ffprobe -v error \
+    -select_streams v:0 \
+    -show_entries stream=codec_name \
+    -of default=noprint_wrappers=1:nokey=1 \
+    "$input"); then
+    die "failed to get codec"
+  fi
 
-ffmpeg -y -i "$input" -vf vidstabdetect=shakiness=10:accuracy=15:result="$trf" -f null - >>"$log" 2>&1 ||
-  die "failed to detect movement"
+  if ! ffmpeg -y -i "$input" -vf vidstabdetect=shakiness=10:accuracy=15:result="$trf" -f null -; then
+    error "failed to detect movement"
+    continue
+  fi
 
-ffmpeg -y -i "$input" -vf vidstabtransform=input="$trf" -c:v "$codec" "$output" >>"$log" 2>&1 ||
-  die "failed to stabilize video"
+  if ! ffmpeg -y -i "$input" -vf vidstabtransform=input="$trf" -c:v "$codec" "$output"; then
+    error "failed to stabilize video"
+    continue
+  fi
 
-rm -f "$trf" "$log"
+  rm -f "$trf"
+done
