handle err

diff --git a/scripts/status/layoutstat b/scripts/status/layoutstat
--- a/scripts/status/layoutstat
+++ b/scripts/status/layoutstat
@@ -3,5 +3,10 @@
 
 layout="$(setxkbmap -query | awk '/layout/{ print $2 }' | sed 's/latam/la/')"
 
+if [ "$?" != 0 ] ; then
+    echo "Failed to get layout"
+    exit 1
+fi
+
 echo "$layout"
 # notify-send -u low --replace-id=12 "󰌌 Layout" "$layout"
diff --git a/scripts/status/netstat b/scripts/status/netstat
--- a/scripts/status/netstat
+++ b/scripts/status/netstat
@@ -22,10 +22,17 @@ int() { # Type of interface & status
     # If down interfaces, exit with icon
     grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null && echo "󰤮" && return 0
     grep -xq 'down' /sys/class/net/e*/operstate 2>/dev/null && echo "󰲛" && return 0
+
+    return 1
 }
 
 # Run 'int'
 icon=$(int)
+
+if [ "$?" != 0 ] ; then
+    echo "Failed to get interface type"
+    exit 1
+fi
 
 # Check if a VPN is enabled
 vpn="$( \
diff --git a/scripts/status/volstat b/scripts/status/volstat
--- a/scripts/status/volstat
+++ b/scripts/status/volstat
@@ -4,6 +4,11 @@
 
 info=$(amixer get Master | grep -m 1 '[0-9]*%')
 
+if [ "$?" != 0 ] ; then
+    echo "Failed to get Master volume"
+    exit 1
+fi
+
 if [ -z "${info##*\[off\]}" ] ; then
     echo "󰖁 ──────────"
     exit 0
